Moyo NV
CombatExtended-Continued/CombatExtended pull request #1034
Opened 2021-09-02 08:27 UTC by Tostov

Adds night vision related stats to moyo stuff.

## Additions

Night Vision for moyo stuff

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-09-02 18:22 UTC, N7Huntsman requested changes
Looks fine, just one minor xml error to fix.

2021-09-02 18:22 UTC, N7Huntsman commented on Patches/Moyo from the depth/Drugs/Belial-V_Effect.xml
> +						<NightVisionEfficiency>0.60</NightVisionEfficiency>
This is adding a duplicate statOffsets.

2021-09-03 10:10 UTC, Tostov commented on Patches/Moyo from the depth/Drugs/Belial-V_Effect.xml
> +						<NightVisionEfficiency>0.60</NightVisionEfficiency>
Should be fixed now.

2021-09-03 18:29 UTC, N7Huntsman approved these changes

2021-09-03 18:29 UTC, merged