Update CompSuppressable.cs
CombatExtended-Continued/CombatExtended pull request #1151
Opened 2021-10-30 22:34 UTC by Taranchuk

## Additions
- No new additions
## Changes
- Cache and fetch BreakThresholdMajor every 30 tick instead of 1 tick.
## References
## Reasoning
- As seen SuppressionThreshold is getting called every tick by IsHunkering and it contains retrieval of BreakThresholdMajor which is a bit heavy method, especially if every humanlike pawn will call it every tick. This is changed to cache and update it every 30 tick which is 0.5 second at normal speed and thus makes basically no difference, but makes the performance impact lighter in 30 times. 
## Alternatives
## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-11-14 03:01 UTC, N7Huntsman approved these changes
No issues in testing.

2021-11-21 20:03 UTC, MadaraUchiha requested changes

2021-11-21 20:03 UTC, MadaraUchiha commented on Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
> +            if (breakThresholdMajorTickCheck == 0 || Find.TickManager.TicksGame > (breakThresholdMajorTickCheck + 30))
Can this not be a simple modulo check against `Find.TickManager.TicksGame`?
```suggestion
            if ((Find.TickManager.TicksGame + 17) % 30 == 0)
```
17 as a random offset to not block the round % 30 too much.

IIRC the game even has a helper method for this exact purpose, although I'm not near the code to tell you which it is.

2021-11-21 20:03 UTC, MadaraUchiha commented on Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
> +            if (currentMoodTickCheck == 0 || Find.TickManager.TicksGame > (currentMoodTickCheck + 30))
Similarly here

2021-11-22 00:05 UTC, MadaraUchiha approved these changes
I take my previous review back. I misread the context in which this is invoked. Thanks @kbatbouta for the heads up 👍

2021-11-22 00:07 UTC, merged