Caulaflower generic ammo
CombatExtended-Continued/CombatExtended pull request #1232
Opened 2021-12-23 16:43 UTC by Caulaflower

## Additions

Generic ammo mode, which groups calibers into generic calibers (like pistol ammo, intermediate ammo, etc.)

## To do
- translation file for settings
- xml for generic ammo types

2022-01-04 21:21 UTC, N7Huntsman submitted a review, later dismissed
Another minor error:
```
Mod CETeam.CombatExtended-genericammo has multiple Verse.ThingCategoryDefs named AmmoHighCaliber. Skipping.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.ThingCategoryDef>:AddAllInMods ()
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType (System.Type,System.Type,string)
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

2022-01-04 21:21 UTC, N7Huntsman commented on Defs/Ammo/GENERIC/LauncherGrenade.xml
> +      <graphicClass>Graphic_StackCountRanged</graphicClass>
These should be `CombatExtended.Graphic_StackCountRanged`.

2022-01-04 21:21 UTC, N7Huntsman commented on Defs/Ammo/GENERIC/LauncherGrenade.xml
> +      <texPath>Things/Ammo0/STACK_RANGED/GrenadeLauncher/SMK</texPath>
Typo here. "Ammo0"

2022-01-04 21:21 UTC, N7Huntsman commented on Defs/Ammo/GENERIC/LauncherGrenade.xml
> +	<detonateProjectile>Bullet_LauncherGrenade_HE</detonateProjectile>
This projectile doesn't exist. Should it be `Bullet_40x46mmGrenade_HE`?

2022-01-04 21:22 UTC, N7Huntsman commented
Regarding some other existing ammo options, with the implementation of this, should we remove the `Simplified Ammo` option?

2022-01-04 21:26 UTC, N7Huntsman commented
Additionally, it currently doesn't swap out the ammo added in scenarios with their generic equivalent.

2022-01-12 19:17 UTC, Caulaflower commented
> Regarding some other existing ammo options, with the implementation of this, should we remove the `Simplified Ammo` option?

in my opinion, there's no need to

2022-01-12 19:18 UTC, albertbokor commented
> Regarding some other existing ammo options, with the implementation of this, should we remove the `Simplified Ammo` option?

ye, it's pretty useless

2022-01-27 12:52 UTC, albertbokor commented
there was some fuckery with the high caliber rounds, renaming it to `AntiMateriel` to be less confusing

2022-01-27 14:22 UTC, albertbokor submitted a review, later dismissed
works great now aside fromthat startup error

2022-01-28 23:24 UTC, perkinslr commented
> Regarding some other existing ammo options, with the implementation of this, should we remove the `Simplified Ammo` option?

They do different things.  Simplified Ammo removes the APHE/AP-I listings, this groups calibers together but *doesn't* remove ammo types within the remaining calibers.  Some people may still want the extra challenge of no AP-I.

2022-01-28 23:27 UTC, perkinslr submitted a review, later dismissed
Does what it says on the tin.  I am concerned about this decreasing the effective damage on some weapons that get their ammo swapped for something weaker, but it's up to the players to either accept that and work around it, or not use the setting.  Same as the no-ammo players.

2022-01-29 16:19 UTC, albertbokor submitted a review, later dismissed
Works flawlessly as I've seen.

2022-01-29 20:40 UTC, perkinslr requested changes

2022-01-29 20:40 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Settings.cs
> +        private bool bipodMechanics = true;
Bipods have their own PR (which was merged), why is this *here*?

2022-01-29 21:27 UTC, perkinslr approved these changes

2022-01-30 08:33 UTC, merged