realism changes
CombatExtended-Continued/CombatExtended pull request #1316
Opened 2022-02-05 18:42 UTC by Caulaflower

## Additions

Makes .410 bore garbage as it should be from a short barrel of stuff like Taurus judge. 

## Reasoning

.410 works like a shotgun in a pisol package in CE considering how next to no mods add other .410 guns other than the Taurus Judge, while in real life it is just a bad pistol, working best with standard .45 Colt

## Alternatives

Putting up with killing bears with a taurus judge

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-02-05 19:52 UTC, N7Huntsman requested changes
I'm fine with the 5.56mm NATO changes. As mentioned, the .410 should probably have a new "slow" projectile set made for short-barrel weapons like the Judge, similar to what the musket ball ammo has.

2022-02-06 11:14 UTC, albertbokor commented
> I'm fine with the 5.56mm NATO changes. As mentioned, the .410 should probably have a new "slow" projectile set made for short-barrel weapons like the Judge, similar to what the musket ball ammo has.

right, I want to update other shotgun ammos too, iirc 16gauge doesn't even have penetration values

2022-02-08 21:01 UTC, albertbokor approved these changes

2022-02-08 21:01 UTC, merged

2022-02-08 21:01 UTC, ItsSamGray approved these changes
LGTM