Pawns' combatPower rebalanced
CombatExtended-Continued/CombatExtended pull request #1407
Opened 2022-03-05 10:58 UTC by ItsSamGray

## Changes

- Removed the patch that tweaked the vanilla mechanoid pawn's combatPower
- Removed the patch that adds cover usage behavior to Lancers
- Tweaked the combatPower of Warcasket pawns from VFE-Pirates

## Reasoning

- Since none of the modded mechanoid pawns are touched combatPower-wise, the change to the vanilla ones in gonna introduce an imbalance in the mechanoid raids when other mech mods are installed. Also, Centipedes are not that deadly.
- Advanced mechs from VFE-Mechanoids have the cover usage behavior, adding a undocumented change to vanilla Lancers only causes confusions.
- Tweaked the combatPower of Warcasket pawns from VFE-Pirates to represent their strength a bit better

## Alternatives

- Leave stuff as is

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors

2022-03-06 03:24 UTC, Breadbox2k19 commented
Why would you remove the cover behaviour from lancers, Lancers are wet noodles and doesn't need to suck harder.

2022-03-06 04:59 UTC, N7Huntsman requested changes
Can't really say that I support many of these changes to the vanilla mechs--at least, certainly not off the cuff like this. Will require a great deal more discussion regarding balance...

2022-03-06 12:19 UTC, Safairette commented
> Why would you remove the cover behaviour from lancers, Lancers are wet noodles and doesn't need to suck harder. Centipedes are super deadly, this change is too subjective and not reflective of most player's experience of CE.

Hard agree. Lancers have very low health and armor and don't have the stopping power of the heavier mechs, relying on outranging with precision weapons. Disabling cover for them directly goes against that role

2022-03-06 14:33 UTC, ItsSamGray commented
> > Why would you remove the cover behaviour from lancers, Lancers are wet noodles and doesn't need to suck harder. Centipedes are super deadly, this change is too subjective and not reflective of most player's experience of CE.
> 
> Hard agree. Lancers have very low health and armor and don't have the stopping power of the heavier mechs, relying on outranging with precision weapons. Disabling cover for them directly goes against that role

Lancers are deadly enough and hit hard enough, they are vanilla level expensive now and their cover seeking behavior which is undocumented and uncalled for made them even a bigger annoyance. Scythers and Centis are back to their old CE values.

2022-03-06 15:55 UTC, Safairette commented
>Lancers are deadly enough and hit hard enough

I don't agree, they are consistent, but their low flesh damage means that they can't reliably down pawns outside of headshots, which are rare

2022-03-10 07:51 UTC, N7Huntsman approved these changes

2022-03-10 07:51 UTC, merged