Insectoids Rebalanced
CombatExtended-Continued/CombatExtended pull request #1410
Opened 2022-03-08 07:13 UTC by ItsSamGray

## Changes

- Rebalanced all the Insectoids from the vanilla game and certain mods like Alpha Animals and VFE-Insectoids

## Reasoning

- Certain armor and move speed values were inconsistent for some insectoids in comparison with their vanilla counterparts. Made sure that these values are brought a bit more in line with what they should be.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] Playtested a colony (specify how long)

2022-03-11 02:32 UTC, N7Huntsman requested changes
Alright, I got about halfway through this PR and reached 44 comments, so I figured I'd subjected myself to enough for now...

I really don't like a lot of these armor increases, honestly. 

I'm very concerned that you're not considering just how tough you're making a lot of these creatures. You have to remember, anything with above 2 - 3 sharp AP is going to be extremely hard to kill melee--you're simply not going to be able to get an arrow or a sword slash through their armor.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_CrepuscularBeetle.xml
> +					<ArmorRating_Sharp>4</ArmorRating_Sharp>
3 sharp is respectable for a non-combat insect. I'd leave the sharp as-is, but you could increase the blunt if you'd like.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_DarkBeast.xml
> +						<ArmorRating_Sharp>2</ArmorRating_Sharp>
The vanilla version of this creature has extremely little armor, and it's CE variants have none. At most, I'd give this 0.2 sharp and 0.4 blunt armor, if I were giving it armor at all.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Demolisher.xml
> +						<compClass>CombatExtended.CompPawnGizmo</compClass>
Honestly, we could probably just nuke the `AmmoUser` on it's just and save ourselves the trouble.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Dunealisk.xml
> +					<ArmorRating_Blunt>8</ArmorRating_Blunt>
See comments on the Animalisk.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_EngorgedTentacularAberration.xml
> -					<PainShockThreshold>1</PainShockThreshold>
Why get rid of this?

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Feralisk.xml
> +					<ArmorRating_Blunt>8</ArmorRating_Blunt>
See comments on the blah blah blah...

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_FrostboundBehemoth.xml
> +					<ArmorRating_Blunt>10</ArmorRating_Blunt>
I'd leave it as-is. 

Big =/= heavily armored, and it's a giant herbivore that's "natural" defense is living where it's too damn cold for anything to come hunt it.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Frostling.xml
> +					<ArmorRating_Blunt>2</ArmorRating_Blunt>
Same as my comments on the Nightbeast; it's essentially a weird warg or wolf. Doesn't need much armor--wouldn't change it.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Frostmite.xml
> +					<ArmorRating_Sharp>2</ArmorRating_Sharp>
Leave it alone. It's a scavenger mite approximately as dangerous as a squirrel.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml
> +					<baseHealthScale>30</baseHealthScale>
So, what exactly is the "recommended" approach to killing one of these things supposed to be if we're making it this tough? This this is already proof against most rifle rounds.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Great_Devourer.xml
> +					<ArmorRating_Sharp>4</ArmorRating_Sharp>
Nah. From the AA wiki: " Their whole name is in fact a pun, since they are not very resilient and are easily dispatched."

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Groundrunner.xml
> +					<ArmorRating_Sharp>1</ArmorRating_Sharp>
It's a hybrid bear/mole, why does it have any armor at all?! The small amount of blunt armor it does have represents a general sturdiness and thick layer of absorbent flesh, essentially.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Ironhusk_Beetle.xml
> +					<ArmorRating_Blunt>42</ArmorRating_Blunt>
Leave it alone. They've already got pretty good armor for something that's not a combat type in the first place.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Junglelisk.xml
> +					<ArmorRating_Blunt>8</ArmorRating_Blunt>
See the blah blah blah...

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Luciferbug.xml
> +					<ArmorRating_Blunt>12</ArmorRating_Blunt>
Leave it. They're intentionally fragile creatures that are dangerous if damaged.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Mammoth_Worm.xml
> -					<ArmorRating_Blunt>26</ArmorRating_Blunt>
Why reduce the armor? Their speed really isn't that impressive, even with the change.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Mantrap.xml
> +					<ArmorRating_Sharp>2</ArmorRating_Sharp>
No. In fact, feel free to remove the armor from this thing entirely. It's a damned _plant_.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MegaLouse.xml
> +					<ArmorRating_Sharp>6</ArmorRating_Sharp>
Leave it. They're intentionally small and fragile. They're intended to be dangerous in a swarm, where a whole bunch can get in close and use their high damage attacks.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Raptor_Shrimp.xml
> +					<ArmorRating_Sharp>10</ArmorRating_Sharp>
Reduce to 7 - 8, so it can be engaged with rifle rounds.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Rayhound.xml
> +					<ArmorRating_Blunt>2</ArmorRating_Blunt>
No. It's a squishy lizard dog.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_RipperHound.xml
> +					<ArmorRating_Blunt>3</ArmorRating_Blunt>
Leave it. It's a squishy wolf-thing on steroids--lucky to have any armor at all.

2022-03-11 02:32 UTC, N7Huntsman commented on Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Thermadon.xml
>  				<value>
I'd leave it. Their armor isn't that impressive.

2022-03-20 11:50 UTC, Caulaflower approved these changes
seems good to me but someone more familiar with xml should probably make sure. That said imo good to go

2022-03-21 15:32 UTC, merged

2022-03-30 04:51 UTC, Breadbox2k19 commented
I'm sorry but what is this? I balanced these animals to have these value for a very good for gameplay consideration, please stop changing them around just because.