Pistol and rifle cartridge rebalanced
CombatExtended-Continued/CombatExtended pull request #1427
Opened 2022-03-19 10:42 UTC by ItsSamGray

## Changes

- Rebalanced certain pistol cartridges based on 0.66/1/2 sharp armor penetration factors
- Rebalanced HP rifle rounds from 0.5x FMJ armor pen to 0.66x 

## Reasoning

- Based on findings for the .44 magnum steel and gel penetration tests, HP and FMJ rounds don't have a 1 to 2 sharp armor penetration relation but something close to 1 to 1.5, so in order to rebalance pistol cartridges in comparison to rifle cartridges and alleviate the arbitrary similarities in sharp pen between them, pistol cartridges received a rebalace.
- In similar vein to the change above, in order to stop rifle HP rounds from severely underperforming in comparison to FMJ ones, the sharp armor penetration of HP rifle cartridges were increased from 0.5xFMJ to 0.66xFMJ

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

2022-03-19 11:01 UTC, Caulaflower submitted a review, later dismissed
Looks goot to me

2022-03-19 11:54 UTC, Caulaflower approved these changes
lgtm

2022-03-19 20:22 UTC, N7Huntsman requested changes
Just leaving a review so this isn't merged right away. I'd like to do some follow-up research on this, and it's more convenient for updating the sheet to have this to look at beforehand if we do merge it.

2022-04-11 04:31 UTC, N7Huntsman commented
To repeat my thoughts as I stated them on the discord;
> Stat tweaks with the research to support it are fine, but I don't currently see a compelling case to change the overall armor penetration ratios between ammo types--certainly not selectively.

2022-04-12 09:08 UTC, closed without merging