Misc. Adjustments
CombatExtended-Continued/CombatExtended pull request #1492
Opened 2022-04-18 18:17 UTC by N7Huntsman

## Changes
Various tweaks and changes to various patches.
- Removed outdated VFWE patch. I can't find a version of the mod for 1.3 anywhere on the workshop and I'm not aware of it being updated anywhere else.
- Cleaned up the ammo patch for VWE to improve load time and resolve a load-order oddity related to VFE: Production's new benches.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-04-18 19:43 UTC, Safairette submitted a review, later dismissed

2022-04-18 19:43 UTC, Safairette commented on Defs/Ammo/Advanced/12GaugeCharged.xml
> -      <pelletCount>6</pelletCount>
Why revert this change? I was done on purpose to differentiate more from the regular 12 gauge, as seen from #652

2022-04-22 06:30 UTC, trikanyo approved these changes
Changes tested

2022-04-23 03:48 UTC, Tostov requested changes
Regarding arrows please (continued) patch
Minor issue with tomahawks is that they still retain the close/ short/medium/long range accuracy stats in their stat block. They also appear to have no sway.

Torch statblock is borked, I'm not sure why in this instance.

2022-04-23 23:52 UTC, Tostov approved these changes
Tomahawks appear to now be fixed.
If torch is unable to be fixed as per info in the discord, should be all good.

2022-04-24 01:59 UTC, merged