Add a reinforced barrel to the Flak Cannon's recipe
CombatExtended-Continued/CombatExtended pull request #1551
Opened 2022-05-05 07:21 UTC by ItsSamGray

## Changes

- What it says on the tin

## Reasoning

- Added the reinforced barrel to the recipe just like how the vanilla mortar is set up for consistency's sake and reducing steel cost bloat.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

2022-05-05 07:24 UTC, N7Huntsman reviewed
The reduced steel cost + barrel requirement seems reasonable to me. Will have to test the difficulty variance bit, as that's new to me, but it looks fine.

2022-05-05 07:27 UTC, ItsSamGray commented
The same PR for the 105mm Howitzer is also opened

2022-05-06 07:23 UTC, albertbokor approved these changes

2022-05-07 06:50 UTC, N7Huntsman requested changes

2022-05-07 06:50 UTC, N7Huntsman commented on Defs/ThingDefs_Buildings/Buildings_Turrets.xml
> +      <Steel>350</Steel>
This throws a start-up error. I'm still looking into the structure of how exactly the structure of this tag works, so I'm not sure what the correct format is.

2022-05-08 04:13 UTC, N7Huntsman commented
Submitted #1553 with the correct xml format.

2022-05-08 04:13 UTC, closed without merging