Ratkin back pack carrying capacity patch
CombatExtended-Continued/CombatExtended pull request #1571
Opened 2022-05-16 14:24 UTC by NyaamZ

Ratkin back pack carrying capacity patch

## Additions

Describe new functionality added by your code, e.g.
- Tribal smoke bombs
- New tribal smoke bomb sprite
- Tribal smoke bomb recipes at smithing bench and crafting spot using prometheum

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Increased regular smoke bomb radius

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #[ISSUE_NUMBER]
- Contributes towards #[ISSUE_NUMBER]

## Reasoning

Why did you choose to implement things this way, e.g.
- Tribals need ways to close distance with pirate raiders
- Smoke bombs allow this while enhancing combat micro
- Thematically appropriate as we already allow tribal prometheum handling
- Easy to implement
- Buffed regular smoke grenades as they are rarely utilized and to justify additional investment

## Alternatives

Describe alternative implementations you have considered, e.g.
- Tribal catapult that launches melee animals into siege camps:
  - Additional use for animals
  - Anachronistic
  - Breaks realism theme

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

2022-05-16 16:46 UTC, N7Huntsman commented
Why is this necessary? As far as I'm aware, CE doesn't utilize 'CarryingCapacity,' using 'CarryBulk' for that purpose instead.

2022-05-16 22:41 UTC, NyaamZ commented
> Why is this necessary? As far as I'm aware, CE doesn't utilize 'CarryingCapacity,' using 'CarryBulk' for that purpose instead.

If carrying capacity is small when pawn works, the movement line will double.
ex) cooking, building

2022-05-23 03:32 UTC, N7Huntsman requested changes
Stat-wise, the changes themselves look fine, but in this case, it'd be preferable to change the patch operations such that we don't touch the original value for the mod, so we don't have to do back and manually adjust these values if the base mod updates.

For the most part, that just means making them Add operations instead of Replace operations..

2022-06-10 23:36 UTC, N7Huntsman commented
I'm going to incorporate these changes into a larger PR removing the carryingCapacity changes throughout the integrated patches.

2022-06-10 23:36 UTC, closed without merging