Arachne Update (Again)
CombatExtended-Continued/CombatExtended pull request #1578
Opened 2022-05-19 10:14 UTC by Airomeda

## Updates

Describe new patches added by your code, e.g.
- Apparel

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-05-20 09:56 UTC, albertbokor approved these changes
LGTM!

2022-05-23 02:12 UTC, N7Huntsman requested changes
What's here generally looks good, but there are two occurrences of duplicate xml tags.

2022-05-23 02:12 UTC, N7Huntsman commented on Patches/Arachne/Apparel_Arachne.xml
> +					<PsychicSensitivity>-0.2</PsychicSensitivity>
This is a duplicate tag.

2022-05-23 02:12 UTC, N7Huntsman commented on Patches/Arachne/ApparelNew_Arachne.xml
> +					<PsychicSensitivity>-0.2</PsychicSensitivity>
This is also a duplicate tag.

2022-05-23 17:37 UTC, Airomeda commented
huhh guess it's overhead on my hand, I'll sort it quickly

2022-05-26 02:22 UTC, N7Huntsman approved these changes

2022-05-26 02:22 UTC, merged