[K4G] Rimworld War 2 - Patch
CombatExtended-Continued/CombatExtended pull request #1660
Opened 2022-07-03 14:27 UTC by Airomeda

## Additions

Describe new functionality added by your code, e.g.
- New Anti-Tank Rockets ammo (Panzerfaust 50 and 60, Type 74mm Rockets)

## Changes

Describe adjustments to existing features made in this merge, e.g.
- None, except my sanity

## References

Links to the associated issues or other related pull requests, e.g.
- None, probably world war 2 reference

## Reasoning

Why did you choose to implement things this way, e.g.
- because yes

## Alternatives

Describe alternative implementations you have considered, e.g.
- nope, this is painful already

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

## Current Issues
- Backpack rendering went borked, I've tried various approaches and to no avail.
- Anti-tank grenade projectiles still not working

2022-07-17 18:06 UTC, albertbokor approved these changes
Seemingly everything working allright for me, pls someone else also chek!

2022-07-17 20:22 UTC, albertbokor approved these changes

2022-07-18 05:30 UTC, N7Huntsman requested changes
You've got a bunch of extraneous changes in here to things like ammo stats and the like. I think maybe you're working off of an older version of dev? In any event, it can't be merged like this.

2022-07-18 05:50 UTC, N7Huntsman reviewed
@Airomeda I'm sorry to put it this way, but _what have you done_ with this patch??? You're using Replace operations to re-write entire Defs instead of simply patching the required values for melee and ranged weapons... just... **_why_**??

Is there something I'm missing here? Otherwise, I'm just baffled--you've submitted a lot of patches, and they've generally been really well done.

2022-07-18 14:36 UTC, closed without merging