Yp updates
CombatExtended-Continued/CombatExtended pull request #1666
Opened 2022-07-05 09:13 UTC by Tostov

## Changes

Changes to the YP dual wield weapons which were reverted to single one handers.

## Reasoning

Doesn't make a lot of sense for them to have some of the doubled stats/characteristics after the adjustment. Also includes a bit of a buff to the pistol, as it functionally lost half its damage and was kind of balanced around that.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-07-05 16:09 UTC, ItsSamGray approved these changes
LGTM

2022-07-05 18:49 UTC, ItsSamGray requested changes
The weapons tags patch is causing a red error, the weapons that are being given the tag must lack a weaponsTag node themselves and are inheriting the node from a parent def so I'd assume the patch should give the weaponsTag node containing the new tags.

2022-07-06 14:51 UTC, ItsSamGray approved these changes

2022-07-09 05:21 UTC, feeddanoob commented
Rimsenal Core got updated again reverting the shard gun change...

2022-07-10 06:20 UTC, ItsSamGray approved these changes

2022-07-10 20:23 UTC, merged