Update/Fix CE's default settings
CombatExtended-Continued/CombatExtended pull request #1683
Opened 2022-07-19 17:39 UTC by ItsSamGray

## Changes

- Changed some of CE's default settings around from false to true and vice versa.

## Reasoning

- Taunts and bullet casing are not very TPS friendly so defaulted them to false
- Manned turrets not breaking shields is a new thing that is beneficial for the player and it being disabled by default goes unnoticed.
- Both left and right clicking on the reload button brings up the ammo selection settings which enabling the "right-click ammo selection" settings allows for faster reloading by just left-clicking.
- Unrealistic cook-off can cause errors during game save state and switching between the setting during that state spawns broken projectiles that throw constant red errors and the only way to remove the errors is to manually find and remove the projectiles. Also bullets flying off everywhere is stupid and unrealistic.
- Weapon and Apparel autopatcher are both unreliable and not robust enough in their current state, so a default disabled state is a better option for now.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (specify how long)

2022-07-19 17:53 UTC, albertbokor approved these changes
:CE_Pray:

2022-07-19 17:54 UTC, perkinslr commented
You also need to chagne them in the save/load section.
`Scribe_Values.Look(ref enableWeaponAutopatcher, "enableWeaponAutopatcher", true);`

2022-07-19 17:55 UTC, perkinslr requested changes
Line 190 ish, 
`Scribe_Values.Look(ref enableWeaponAutopatcher, "enableWeaponAutopatcher", true);` needs to be `Scribe_Values.Look(ref enableWeaponAutopatcher, "enableWeaponAutopatcher", false);` (same for the other settings too).

2022-07-19 17:58 UTC, perkinslr commented
Don't ask me *why* it's set up this way, blame Tynan.  But you need to set the default setting (which you did) in order for the setting to be correct at start of a new game.  You *then* need to set it when Scribe_Values goes to read the value from a save game, or it will be wrong if the save game didn't have the value written out previously.  This matters *most* when adding new options, but the two should be kept consistent for sanity.

2022-07-19 18:21 UTC, Safairette requested changes
Not agreeing with a bunch of changes here:

- Taunts and casings: minor performance impact isn't a causes to disable a feature by default, that's why you can disable them yourself
- Turrets breaking shields: more of a balancing thing than a qol change, but that's minor
- Realistic cook-off: Better to fix the bug rather than sweeping it under the rug, using it as a point to support your subjective opinion is kinda questionable
- Ammo and autopatchers: no issues there

2022-08-10 01:10 UTC, N7Huntsman approved these changes

2022-08-10 02:03 UTC, merged