Caulaflower give ammo2
CombatExtended-Continued/CombatExtended pull request #1690
Opened 2022-07-26 13:23 UTC by Caulaflower

## Additions

Ammo giving PR. Remade #1416 without mortar stuff

2022-08-04 01:43 UTC, perkinslr submitted a review, later dismissed
Unless I'm missing something, this lets the player force ammo into wildlife.  As neat as it might be to stick a couple antigrains onto a boomrat and turn it loose...  We should probably check if the target can use the ammo if it isn't a player pawn.

2022-08-04 01:44 UTC, perkinslr commented
If that is more work than you want to do at the moment, I'm happy to approve this for merging, and then follow it up with the needed checks, since I can't directly edit the source branch.  I could also do it as a PR against your source branch if you want.

2022-08-05 10:59 UTC, ItsSamGray approved these changes
LGTM, gotta add the comp to baseline human in this PR or the next one which will be opended for the XML implementation of the system.

2022-08-05 13:44 UTC, ItsSamGray approved these changes

2022-08-05 23:04 UTC, perkinslr requested changes

2022-08-05 23:04 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Comps/CompAmmoGiver.cs
> +    public class Building_WorkTableSmoking : Building_WorkTable
This does not look related to this PR.

2022-08-05 23:19 UTC, perkinslr approved these changes

2022-08-06 06:13 UTC, ItsSamGray approved these changes

2022-08-06 06:14 UTC, merged