Lemolim Race Patch
CombatExtended-Continued/CombatExtended pull request #1725
Opened 2022-08-07 20:46 UTC by Deustodo

## Additions

Added patches for Scenario, Race, body, gizmo and Pawnkind.

## Changes

Added a Tribal Grenadier Pawnkind to use Stickybomb.

## References

Values for the leather I based one used in Alpha Animals of similar insulation. (chameleon yak)

## Alternatives

## Testing

Check tests you have performed:
- [x ] Compiles without warnings
- [x ] Game runs without errors
- [x ] (For compatibility patches) ...with and without patched mod loaded
- [x ] Playtested a colony (8 hours)

2022-08-09 22:56 UTC, N7Huntsman requested changes
Some feedback.

2022-08-09 22:56 UTC, N7Huntsman commented on Patches/Lemolim Race/Lemolim_Race.xml
> +			<li Class="PatchOperationReplace">
This should be in its own file.

2022-08-09 22:56 UTC, N7Huntsman commented on Patches/Lemolim Race/Lemonim_Pawnkind.xml
> +				<li>MedievalMeleeAdvanced</li>
This should probably be a Neolithic tag, given the low tech level of the rest of their gear.

2022-08-09 22:56 UTC, N7Huntsman commented on Patches/Lemolim Race/Scenarios_Patch.xml
> +						<count>35</count>
Increase to 70, please.

2022-08-09 22:56 UTC, N7Huntsman commented on Patches/Lemolim Race/Scenarios_Patch.xml
> +						<thingDef>Ammo_Arrow_Steel</thingDef>
If you would, make these stone arrows and give them 50.

2022-08-10 00:58 UTC, Deustodo commented
Made all the changes. Originally I put 35 ammo for the autopistol because of the this part in the Scenario description.
"Seeing this as an opportunity to escape, the three make a beeline to the escape pods, dodging any threats that came their way. **An autopistol was grabbed by one of them from a fallen pirate's grasp before they escaped.** The prisoner ship exploded shortly after."

Either way, I made the change.

2022-08-11 23:08 UTC, N7Huntsman requested changes
Looks good, but the Lemolin_Leather file needs to be an xml file.

2022-08-11 23:25 UTC, N7Huntsman approved these changes

2022-08-11 23:25 UTC, merged