Scale bullet damage based on launcher quality
CombatExtended-Continued/CombatExtended pull request #1916
Opened 2022-10-09 16:12 UTC by mszabo-wikia

## Additions

Apply a multiplier to bullet damage based on the quality of the weapon that fired it, just like vanilla does. This uses the RangedWeapon_DamageMultiplier vanilla stat.
## References

- Closes #1867

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-10-09 20:35 UTC, SamaelGray commented
Works as intended in-game, will approve after the last 1.3 release.

2022-10-10 15:58 UTC, T-rexsuper1 commented
holy crap is this a dream

2022-10-11 21:16 UTC, SamaelGray approved these changes

2022-10-14 04:28 UTC, SamaelGray submitted a review, later dismissed

2022-10-20 16:23 UTC, SamaelGray submitted a review, later dismissed

2022-10-27 20:38 UTC, perkinslr requested changes

2022-10-27 20:38 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Lasers/LaserBeamCE.cs
> +        public override int DamageAmount
Why is this being converted *back* to an int?  We'll likely be moving all bullet damage to floats eventually, no reason to add more work later for lasers.

2022-10-27 20:38 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
> +        public virtual int DamageAmount
Should return a float.  We use floats internally for damage calculations.  It's a limitation of Core that base weapon damage are integers, but this is an ideal place to make them floats, and will make converting the base damage to floats in the future easier.

2022-10-28 22:12 UTC, SamaelGray approved these changes

2022-10-30 09:56 UTC, Thorbane approved these changes

2022-10-30 10:05 UTC, merged