Remove mech weapon textures
CombatExtended-Continued/CombatExtended pull request #1939
Opened 2022-10-20 13:25 UTC by SamaelGray

## Changes

- What it says on the tin.
- Removed the `GunDrawExtension` so that the mech weapon don't look excessively and unnecessarily big.

## References

- Closes https://github.com/CombatExtended-Continued/CombatExtended/issues/1865

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

2022-10-21 21:52 UTC, albertbokor submitted a review, later dismissed

2022-10-21 22:38 UTC, N7Huntsman requested changes
Hold-off on removing the mech textures until we've got a plan in mind and have had the opportunity to get a sense of the Biotech mech weapons.

2022-10-29 16:50 UTC, albertbokor approved these changes

2022-11-03 18:32 UTC, albertbokor approved these changes
will figure something nice and style consistent out when we have too much time

2022-11-03 18:32 UTC, merged