Fix black smoke rendering and propagation
CombatExtended-Continued/CombatExtended pull request #1954
Opened 2022-10-23 16:56 UTC by mszabo-wikia

## Changes

Black smoke uses the pre-1.4 object gas system, which is still present in core, but the BaseGas def has been removed along with some fields from GasProperties. Augment the smoke def with missing data that used to be in the base def, and introduce a new CE-specific gas property class to store the fields removed from core GasProperties.

This does not yet fix the interaction of combat with black smoke - we should do that in a followup patch.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony - started a fire on a test map and verified the rendering and propagation for black smoke.

2022-10-24 06:07 UTC, N7Huntsman submitted a review, later dismissed

2022-10-27 18:04 UTC, perkinslr requested changes
Need to *not* rebuild the 0CombatExtendedLoader.dll unless you are actually changing files inside the Loader project, and in that case, it is best to re-upload a loader built by github actions.

2022-10-28 02:17 UTC, perkinslr approved these changes

2022-10-28 07:34 UTC, SamaelGray approved these changes

2022-10-28 12:13 UTC, merged