Barbed wire tweaks and retexture
CombatExtended-Continued/CombatExtended pull request #1959
Opened 2022-10-24 21:36 UTC by SamaelGray

## Changes

- Changed the barbed wire's recipe from 1 wood + 1 steel to x1 `Metallic/Woody` and x1 steel.
- Changed the filthLeaving to SlagRubble which fits the barbed wires better.
- Added a CE_ prefix to the building defNames.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (specify how long)

2022-10-24 23:08 UTC, N7Huntsman requested changes
Since the graphic is being made with a mask (for the poles), I believe we're going to make it a Stuffable thing. Woody and Metallic would be appropriate I think.

2022-10-25 04:10 UTC, SamaelGray commented
> Since the graphic is being made with a mask (for the poles), I believe we're going to make it a Stuffable thing. Woody and Metallic would be appropriate I think.

Nah it won't be, we don't want wooden and golden barbed wires that ave abysmal HP, both the pole and wire are Steeled and the same material as said in the reasoning section for QoL's sake.

2022-10-25 12:41 UTC, albertbokor approved these changes

2022-10-25 15:40 UTC, albertbokor approved these changes

2022-10-25 15:40 UTC, merged