Patch the new mechanoid weapons
CombatExtended-Continued/CombatExtended pull request #1962
Opened 2022-10-25 17:26 UTC by SamaelGray

## Additions

- Patched the new light weapons, the rest to come.

## References

- https://docs.google.com/spreadsheets/d/1lbT0zzagCRPDJG4GctkeeoTsFCt3lYfM4SRnWt8ql-k/edit#gid=1573763037

## Reasoning

- Chose 16 gauge shells for the mini-shotgun cuz 20 gauge is too small and the gun is not a normal sized shotgun to accept 12 gauge.
- The Slugthrower is similar to the vanilla assault rifle hence 5.56.
- The Spiner is a short very range gun, 5.7x28mm without an ammoset seemed fitting since the round is potent enough and  the War Urchin mechs don't stick around in the colony.
- Although the Mini-flameblaster works as intended even unpatched, it made sense to patch it similar to a normal CE flamethrower for better reliability.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2022-10-31 08:37 UTC, Tostov requested changes
Regular needlegun is using caseless toxic ammoset instead of regular caseless. needs to be fixed.

2022-11-02 03:03 UTC, N7Huntsman submitted a review, later dismissed
Some questions and feedback.

2022-11-02 04:44 UTC, SamaelGray commented on Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
> +  <Operation Class="PatchOperationReplace">
Cuz the operation fails to replace the custom verbClass of the flameblaster resulting in two attack verbs in-game...

2022-11-02 04:46 UTC, SamaelGray commented on Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
> +      <defaultProjectile>Bullet_16Gauge_Buck</defaultProjectile>
As specifically mentioned in the reasoning section, 20 gauge is too weak and small for a _mini_ shotgun, it's not a micro shotgun and 12 gauge is too big for a mini shotgun that deals less damage than normal shotguns in vanilla and visibly fires less pellets.

2022-11-02 04:47 UTC, SamaelGray commented on Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
> +      <magazineSize>10</magazineSize>
Fair, I'd go for 6~8

2022-11-02 04:48 UTC, SamaelGray commented on Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
> +      <RangedWeapon_Cooldown>0.37</RangedWeapon_Cooldown>
The mech itself can't reload weapons regardless of having an ammoset or not, it's not smart enough on purpose. Can adjust the fire rate if it seems too high.

2022-11-02 13:25 UTC, Tostov commented
Seems to be working without issues so far. Haven't run into the grazer yet to fully test, but based on the Diabolus I assume it's working mostly without issues.

2022-11-03 02:40 UTC, N7Huntsman approved these changes
Players might want a longer cooldown on the beamer depending upon how well the mech performs in combat, but given that the beam is only so-so currently due to how the vanilla verb works, I think it's fine for now.

2022-11-03 02:44 UTC, N7Huntsman submitted a review, later dismissed
Fixed a typo.

2022-11-03 17:06 UTC, albertbokor approved these changes
Warqueen and entourage sufficiently fucks!

2022-11-03 17:19 UTC, merged