Compatibility patches for Star crafter's armory, vanilla XCOM weapons, and infinity rim: Ariadna
CombatExtended-Continued/CombatExtended pull request #1976
Opened 2022-10-28 10:30 UTC by CMDR-Bill-Doors

## Additions

- Patches for Star crafter's armory
- Patchs, ammo sets and ammo sprite for Infinity rim: Ariadna
- Patches and ammo sets for vanilla XCOM weapons

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] with and without patched mod loaded
- [ ] Playtested a colony

2022-10-28 16:20 UTC, databobek commented
I've playtested a colony and didn't find any issues

2022-11-03 21:26 UTC, albertbokor commented
CMC-300 breaks ui, it's unequipped item's infopanel is empty and breaks render of character editor ui and error log when equipped

2022-11-03 21:29 UTC, albertbokor commented
irrelevant sidenote: Ariadna textures look very fried, who would want to play with this?

2022-11-14 19:50 UTC, albertbokor submitted a review, later dismissed

2022-11-18 02:24 UTC, N7Huntsman requested changes
- The vodka bottle from Ariadna has a melee attack that needs patched.

2022-11-18 02:24 UTC, N7Huntsman commented on Patches/Star Crafter's Armory/CMC300.xml
> +						<ToxicSensitivity>-0.5</ToxicSensitivity>
This tag is no longer used--it should be `<ToxicEnvironmentResistance>0.5</ToxicEnvironmentResistance>` instead.

2022-11-28 07:15 UTC, SamaelGray approved these changes

2022-11-28 07:15 UTC, merged