Animal baseHealthScale patch removal
CombatExtended-Continued/CombatExtended pull request #2035
Opened 2022-11-10 20:38 UTC by SamaelGray

## Changes

- Removed the `baseHealthScale` patches for base game and modded animals (except Insectoids for now).
- Cleaned up some leftover `baseBodySize` patches for animals.
- Deleted the depreciated patch folder for the Genetic Rim mod.

## Reasoning

- https://discord.com/channels/278818534069501953/700236703180259358/1039484163352436837

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [x] Playtested a colony
https://discord.com/channels/278818534069501953/322827713335394304/1040325557663051796

2022-11-10 21:02 UTC, albertbokor submitted a review, later dismissed

2022-11-14 01:44 UTC, N7Huntsman requested changes
Will give this a glance.

2022-11-27 20:17 UTC, N7Huntsman requested changes

2022-11-27 20:17 UTC, N7Huntsman commented on Patches/Core/ThingDefs_Races/Races_Animal_Giant.xml
> -			<baseHealthScale>5</baseHealthScale>
The vanilla Thrumbo basehealthScale is only 0.7. Given the threat they're intended to present, I think the health and combat power patches for it should stay.

2022-11-27 20:17 UTC, N7Huntsman commented on Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml
> -			<combatPower>20</combatPower>
Vanilla combat power is 70, meaning one tortoise is equivalent to a little less than a lynx (80), which I think is kind of absurd. I'd probably leave this patch as it is.

2022-11-27 20:18 UTC, N7Huntsman commented
Generally looks alright for the Core animals, with a few bits of specific feedback. Haven't given the mod patches more than a glance, but the seem much the same.

2022-11-27 21:22 UTC, N7Huntsman approved these changes

2022-11-27 21:45 UTC, merged