save equip stat
CombatExtended-Continued/CombatExtended pull request #2099
Opened 2022-11-23 15:58 UTC by Cn-mjt44

Issues#

2022-11-23 16:09 UTC, Cn-mjt44 commented
https://github.com/CombatExtended-Continued/CombatExtended/issues/2098

2022-11-28 19:45 UTC, perkinslr requested changes

2022-11-28 19:45 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Comps/BipodComp.cs
> +			CanSetUp = true;
This is never cleared.  So when you start a game or load a save, it's false until the comp gets equipped, at which point it is true until the next game load.  

If you want to go this approach, CanSetUp needs to be set in notify_equipped, cleared in the uniquipped function, and stored/loaded on game save.  

A likely better approach is to make CanSetUp a getter, and have it check if the comp is held by a pawn dynamically.  It should be cheap enough to not need caching, but could be cached if it proves expensive.

2022-12-05 03:55 UTC, Cn-mjt44 commented
looks like game fix it inside

2022-12-05 03:55 UTC, closed without merging