Check verbs rather than CompAmmoUser when initializing weapons
CombatExtended-Continued/CombatExtended pull request #2451
Opened 2023-04-22 13:27 UTC by masakitenchi

Now checks any verb that's assignable from Verb_LaunchProjectileCE

## Changes

See issue #2450 

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #2450 

## Reasoning

Usually when running out of ammo enemies are close enough, and in that case using a grenade as melee weapon should only happens when in desperate situation (e.g. having no melee weapon), and when having a better alternative (melee weapon in this case), it's reasonable that pawn switch to melee weapon rather than grenade.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

2023-05-04 02:50 UTC, Thorbane approved these changes

2023-05-07 18:55 UTC, N7Huntsman requested changes
I get the following error in testing. I'm not sure whether or not it's directly related to these changes or simply a different problem we've stumbled into.
https://pastebin.com/ag4LWDam

I had an undrafted shooter in the 'Attack' behavior firing at a melee-enemy. They had a knife and frag grenades in their inventory. When they ran out of ammo or when their LoS to the target was interrupted, they did no switch weapons and that error started spamming in the log as the shooter froze.

2023-05-08 11:32 UTC, masakitenchi commented
> I get the following error in testing. I'm not sure whether or not it's directly related to these changes or simply a different problem we've stumbled into. https://pastebin.com/ag4LWDam
> 
> I had an undrafted shooter in the 'Attack' behavior firing at a melee-enemy that began on the other side of an embrasure. The shooter had a knife and frag grenades in their inventory. When they ran out of ammo or when their LoS to the target was interrupted, they did not switch weapons and that error started spamming in the log as the shooter froze. When LoS was restored or when their magazine was refilled (via dev commands), they resumed firing and the error went away.

Reproduced *in dev branch* w/o rocketman & VFE Core since they patches various Tick() methods:
|Status|Link|
|-|-|
|With Rocketman & VFE Core|https://gist.github.com/masakitenchi/6e2e38b0d1c7dd3a253a69c558cbd2d7|
|Without Rocketman & VFE Core|https://gist.github.com/masakitenchi/5c9619d6f443bf7f4e084732d9f75e87|

But I have no idea how to 100% reproduce this error without trying multiple times, so I'll leave this bug report to someone else

2023-06-15 06:23 UTC, N7Huntsman approved these changes

2023-06-15 06:23 UTC, merged