VFE - Deserters patch
CombatExtended-Continued/CombatExtended pull request #2721
Opened 2023-08-27 18:01 UTC by SamaelGray

## Changes

- What it says on the tin.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2023-08-28 19:42 UTC, Thorbane approved these changes

2023-08-28 20:42 UTC, HeraldOfTzeentch commented
appears the xml for the turrets throws errors upon startup and isnt working

2023-08-28 21:20 UTC, albertbokor approved these changes

2023-09-11 03:47 UTC, mlg6662 reviewed
hi :3

2023-09-17 01:22 UTC, N7Huntsman approved these changes

2023-10-18 17:10 UTC, Safairette requested changes
One oversight to be fixed and one potential balancing issue.
Otherwise looks good to me.

2023-10-20 14:50 UTC, Safairette commented on Patches/Vanilla Factions Expanded - Deserters/RangedSpacer.xml
> +					<xpath>Defs/ThingDef[defName="VFED_Gun_ChargeCycler"]/verbs</xpath>
Removed the duplicate patch

2023-10-26 04:19 UTC, N7Huntsman approved these changes

2023-10-26 04:28 UTC, N7Huntsman approved these changes

2023-10-26 06:15 UTC, SamaelGray commented on Patches/Vanilla Factions Expanded - Deserters/Contraband.xml
> +				<xpath>Defs/ThingDef[defName="Ammo_5x35mmCharged"]</xpath>
Ammo for a weapon that is unusable in CE?

2023-10-26 06:53 UTC, Safairette approved these changes
Contraband doesn't respect generic mode at the moment, but otherwise seems to work fine now.

2023-10-27 04:04 UTC, N7Huntsman approved these changes

2023-10-27 08:08 UTC, SamaelGray commented
The CEG charge sniper and its ammo are not added to the contraband list yet.

2023-10-27 09:26 UTC, N7Huntsman commented
Whoops, was working on spotty wifi and the commit got hung up. There we go.

2023-10-27 18:18 UTC, Safairette approved these changes

2023-10-27 18:48 UTC, N7Huntsman approved these changes

2023-10-27 18:48 UTC, merged