Update WorldObjectDamageWorker.cs
CombatExtended-Continued/CombatExtended pull request #2751
Opened 2023-09-12 19:13 UTC by CMDR-Bill-Doors

## Changes

Makes damage field in shellingproperties replace evaluated damage instead of multiply it

## Reasoning

Imagine, now we have a nuclear LGIS missile dealing 1.145 x E^-14 damage to a tribe tent, which isn't much. I wrote <damage>1000</damage>, expecting damage to be 1000, but it's not. It's 1.145 x E^-11.
If someone wanted to code a projectile's damage, one have to know how many damage it does before coding, and for those without the few hardcoded damage types, usually none.
Changing it from result *= damage to result = damage makes it more sensible for anyone who intend to change a projectile's shelling damage, especially those that doesn't do any damage before.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2023-09-21 20:11 UTC, MaxDorob commented
Originally this damage property was used as a mulitplier for damage.
Check 155mm howtizer

2023-10-06 08:49 UTC, N7Huntsman reviewed
It looks like this turns only the `damage` tag into a flat overwrite rather than a factor? I'm onboard with the change--it's more straightforward for cases where we want fine control over a shell's properties, and the existing auto calculations for damage generally have us covered for most cases.

However, it doesn't appear to be working (if I'm understanding the override `damage` correctly). If I add an overwrite value of 15 to a shell and fire it at a settlement, it should do 15 damage to the settlement's HP, is that correct?

Because, at present shells with a custom damage value of about 70 are only doing 0.003 damage to the settlement. Setting the value to 200 increased the damage done to 0.005. Is it intended for the overwrite to work that way?

2023-10-13 06:06 UTC, N7Huntsman commented
No issues in testing, but I think there's some damage value scaling that might still need to be done in the xml?

2023-10-19 04:43 UTC, N7Huntsman requested changes
Copied remarks from Discord:
From a bit more testing of #2751, the xml value of damage set for shells is not translating to the HP damage dealt to settlements. I'm testing values of 10 and it's dealing 500+ damage, wiping out Empire settlements in one hit.

2023-10-19 04:43 UTC, N7Huntsman commented on Source/CombatExtended/CombatExtended/WorldObjects/WorldObjectDamageWorker.cs
>              result /= 3500f;
Are we actually dividing the xml-defined damage by the factor of 3500? Or is it only being applied to the damage being automatically calculated from the shell properties?

2023-10-24 10:50 UTC, N7Huntsman approved these changes
No issues in testing, and the change from a multiplier to a flat override is easier to wrangle from a balancing perspective.

2023-10-24 10:53 UTC, mszabo-wikia approved these changes

2023-10-26 02:21 UTC, merged