Ask VF to notify us when a shot is fired
CombatExtended-Continued/CombatExtended pull request #2776
Opened 2023-09-22 23:54 UTC by perkinslr

## Additions

Generates filth and motes when vehicle turrets fire.

## References

Second half of #2772 

## Testing

Check tests you have performed:
- [X] Compiles without warnings
- [X] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2023-10-19 06:58 UTC, N7Huntsman commented
Currently awaiting an update of the VF Steam release to be tested and merged.

2023-10-23 06:41 UTC, N7Huntsman requested changes
With the current Steam release of VF, throws a start-up error and prevents the vehicle from firing.

Log: https://pastebin.com/kejZrEvt

2023-11-14 01:17 UTC, N7Huntsman approved these changes
Works as intended, spawning casing motes and the associated filth. Tested using the Steam version of VF.

2023-11-14 01:51 UTC, trikanyo approved these changes

2023-11-14 01:58 UTC, merged