Vehicle Framework Armor
CombatExtended-Continued/CombatExtended pull request #2822
Opened 2023-10-19 00:09 UTC by perkinslr

## Changes

Vehicle's handle hit location and armor properly

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

2023-10-22 21:55 UTC, trikanyo commented on Source/VehiclesCompat/VehiclesCompat/VehicleArmorPatch.cs
> +	    if (Controller.settings.patchArmorDamage)
invert check to get rid of if else

2023-10-23 06:09 UTC, trikanyo submitted a review, later dismissed

2023-10-23 07:59 UTC, N7Huntsman requested changes
No errors associated with it, but the ammo system options are not appearing on the CE main menu mod settings panel with this assembly. https://i.imgur.com/6X6ggt1.jpg

2023-10-23 11:52 UTC, SerinaCE commented
server down

2023-10-26 05:13 UTC, N7Huntsman approved these changes
Everything works in normal, generic, and no ammo modes. The issue with the mod menu panel has been resolved.

2023-10-26 08:02 UTC, merged