DefOf cleanup
CombatExtended-Continued/CombatExtended pull request #2978
Opened 2024-02-04 23:54 UTC by Safairette

## Additions

- Added `DefOfHelper.EnsureInitializedInCtor` to all DefOf files. This should provide a warning if any DefOf is accessed before it's ready.

## Changes

- Replaced several def database lookups with DefOf references. This should shave off a bit of performace from the calculations.
- Refactored the DefOf files to be categorized only by their def classes, replacing the usages where necessary.
- Changed some stat DefOfs to the correct vanilla format from the previous self-assignment
- Removed unused references from the `using` section of the DefOf files.

## Reasoning

- Categorizing DefOfs by def class gives a more clear direction and is more in-line with the vanilla implementation.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] Playtested a colony (specify how long)

2024-03-11 20:37 UTC, MaxDorob approved these changes

2024-03-13 23:31 UTC, N7Huntsman requested changes
As discussed in discord, getting a warning for `CE_BodyShapeDefOf`. Not overly concerning, but we may as well resolve it while we're poking at this stuff, and save ourselves getting asked about it in the future.

https://pastebin.com/itiaGy5D

2024-03-16 04:26 UTC, N7Huntsman approved these changes

2024-03-16 09:16 UTC, MaxDorob approved these changes

2024-03-16 19:04 UTC, merged