Patch Anomaly DLC (wip)
CombatExtended-Continued/CombatExtended pull request #3105
Opened 2024-04-23 22:53 UTC by N7Huntsman

## Additions
Dummy PR for tracking/testing purposes.
- Patch new Anomaly content to work with CE.

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Increased regular smoke bomb radius

## Reasoning
- Because the Cube wills it.
- 
## Alternatives
None, really.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2024-04-25 14:50 UTC, SaltyKarl commented
mortar shell Recipe's </fixedIngredientFilter> does not have Bioferrite in it

2024-05-07 11:25 UTC, SamaelGray commented
I propose adding a bioferrite flamer fuel to the incinerator's own ammoset or a new one specific to it that deals high burn damage, more than prometheum and chemfuel, but does not spawn puddles. I can make the weapon distinct and keeps the bioferrite fuel of vanilla included in the CE version. The same fuel type can be used for the Hellcat too.

2024-05-11 07:39 UTC, SamaelGray commented
The lab coat description mentions pockets, a +10 bulk capacity would make sense.

2024-05-17 07:52 UTC, SamaelGray commented on Anomaly/Defs/Ammo/NerveSpikerBolt.xml
> +			<armorPenetrationSharp>5</armorPenetrationSharp>
The sheet states 2.5mm, is this a typo or is it intended?
Plasteel bolts have 3.5mm AP so ~3mm would make sense unless there's a reason behind the 5.

2024-05-17 07:54 UTC, SamaelGray commented on Anomaly/Defs/Ammo/NerveSpikerBolt.xml
> +			<preExplosionSpawnChance>0.25</preExplosionSpawnChance>
Would bump to higher than 0.5.

2024-05-17 07:57 UTC, SamaelGray commented on Anomaly/Defs/Ammo/NerveSpikerBolt.xml
> +			<speed>34</speed>
My revised formula states 28, the same formula currently in use for all arrows and bolts.

2024-05-17 08:07 UTC, SamaelGray commented on Anomaly/Patches/Misc/Mutants.xml
> +  <Operation Class="PatchOperationReplace">
The whole file is using the wrong indentation style.
I'd assume the ghouls have bioferrite claws and bump the sharp AP on their scratch attacks, probably increase the damage too. Something close to an unpowered power claw.
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/56392968/fa83bb6c-e7f3-43e7-b8c2-c46151509e0e)

2024-05-17 08:12 UTC, SamaelGray commented on Anomaly/Patches/ThingDefs_Misc/Apparel_Packs.xml
> +			<dropsCasings>true</dropsCasings>
No need for casings as it's not a grenade, looks pretty much like a stick flare.

2024-05-17 08:14 UTC, SamaelGray commented on Anomaly/Patches/ThingDefs_Misc/Weapons_Ranged.xml
> +	<Operation Class="CombatExtended.PatchOperationMakeGunCECompatible">
To be switched to a Galil ACE in 5.56 low velocity ammoset with the appropriate texture.
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/56392968/20b951a3-8fdb-4e32-bd07-f5cf008b97b9)

2024-06-02 07:04 UTC, SamaelGray commented on Anomaly/Patches/ThingDefs_Misc/Weapons_Ranged.xml
> +			<defaultProjectile>Bullet_556x45mmNATO_FMJ</defaultProjectile>
Set to normal ammoset and projectile, should be the short-barrel (_SB) version

2024-06-11 08:29 UTC, MaxDorob submitted a review, later dismissed
Code looks good

2024-06-13 14:30 UTC, SamaelGray commented
Crossbow bolts and crossbows themselves like the Spiker are commonly considered medieval, wouldn't it be more appropriate for the Spike bolts' (bioferrite _arrows(?)_ bolts) texture path to be inside the Medieval folder?

2024-06-19 17:23 UTC, Tostov requested changes
Overall seems workable, haven't run into any major bug issues from a decent amount of colony time (haven't tested all events in regular play but most have been completed in devmode quickly testing).
Entity downing seems to be a little odd since a lot of them tend to go down very quickly but just barely, and often get back up shortly afterwards. But otherwise not problematic as far as I have experienced.
As noted in the other note, noctol just needs its add changed to a replace and then I can't see any other specific issues with operation of the branch/patch.

2024-06-19 17:23 UTC, Tostov commented on Anomaly/Patches/ThingDefs_Races/Races_Entities_Misc.xml
> +	<Operation Class="PatchOperationAdd">
Requires a replace op as it does start with armor already in vanilla so trying to patch add leaves them with vanilla armor value.

2024-06-20 12:44 UTC, Tostov approved these changes

2024-06-20 12:48 UTC, Tostov requested changes
Deadlife pack currently does not consume charges.
In vanilla it is single use and disposable.
I'm not sure if we have a one use variant of the static launch verb we use on apparel.
If not we could just force it to use/reload with deadlife shells, which is sensible but does significantly increase the power of the pack (and consequentely reduce the effective strength of the creep joiner that has the deadlife ability).

2024-06-21 03:13 UTC, Tostov approved these changes

2024-06-21 03:15 UTC, Tostov commented
All tested equipment/abilites seem to be working without issues now. Able to complete a playthrough without any gamebreaking issues arising outside of those now resolved.

2024-06-21 16:15 UTC, merged