Updated SOS2 Patch
CombatExtended-Continued/CombatExtended pull request #3182
Opened 2024-06-09 04:29 UTC by Rhinous

## Additions

- Added support for SOS2 shields to intercept ProjectileCE
- TODO: patch ship weapons on the ground 

## Changes

- Updated SOS2 Reference assembly
- Updated SOS2 Torpedo tube reload patch

## References

- Closes #3173 

## Reasoning

- Makes CE and SOS2 compatible

## Alternatives

- Leave it unpatched

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2024-07-04 16:52 UTC, N7Huntsman requested changes
Torpedo reloading job needs some attention, as it doesn't currently recognize torpedos as usable ammo and reports 'no torpedo' when trying to have a colonist load the launcher. Once loaded however, the torpedos fire correctly.

Shields are correctly intercepting CE projectiles and landed turrets are working.

2024-07-09 18:38 UTC, N7Huntsman submitted a review, later dismissed
Torpedos are now working, seems good to go.

2024-07-09 21:03 UTC, MaxDorob requested changes

2024-07-10 04:15 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/SOS2Compat.cs
> +        }
Added

2024-07-10 04:51 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/SOS2Compat.cs
> +                }
Merged the logic into the one method

2024-07-10 04:52 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/SOS2Compat.cs
> +                    exactPosition = BlockerRegistry.GetExactPosition(projectile.OriginIV3.ToVector3(), exactPosition, new Vector3(shield.parent.Position.x, 0, shield.parent.Position.z), shield.radius
using the result of the intersectionpoint check from further up now

2024-07-10 04:52 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/SOS2Compat.cs
> +            }
Switched to using IntersectionPoint

2024-07-10 04:53 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/Building_ShipTurretCE.cs
> +    public class Building_ShipTurretCE : Building_Turret
Fixed the inheritance

2024-07-10 04:53 UTC, Rhinous commented on Source/SOS2Compat/SOS2Compat/Building_ShipTurretCE.cs
> +        }
Fixed the inheritance

2024-07-10 04:58 UTC, Rhinous commented
Inheritance should be sorted now to not have a ton of duplicated code, shield logic also updated.

2024-07-16 18:16 UTC, N7Huntsman approved these changes

2024-07-16 18:29 UTC, N7Huntsman approved these changes
Works in testing.

2024-07-17 08:16 UTC, Rhinous commented
Split some functionality into #3278 and #3279 will need to add the ground defense mode logic to another PR afterwards

2024-07-18 11:19 UTC, Rhinous commented
Cleaned up and added GroundDefenseMode functionality to #3282 making this now obsolete

2024-07-18 11:19 UTC, closed without merging