Orassans
CombatExtended-Continued/CombatExtended pull request #321
Opened 2020-10-13 02:33 UTC by onigamii

## Changes
- Updated the Orassans patch and patched in the new DMR.
- Orassan Heavy Pistol ammo from 12x64 to 8x35mm.
- Orassan SMG ammo from 6x24mm to 6x18mm.
- Added custom projectile for the Cryo Launcher (CL is an ultra tech weapon so i didn't give it an ammoSet).

## Testing

- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested

2020-10-13 22:16 UTC, N7Huntsman requested changes
The cat's eye juice bottles needs its tools patched in line with other alcohols. The cryo launcher, missile launcher, and shotgun also needs a melee patch.

2020-10-13 22:16 UTC, N7Huntsman commented on Patches/Orassans/ThingDefs_Misc/Apparel_Hats.xml
> +					<xpath>/Defs/ThingDef[defName="Apparel_OrassanPowerArmorHelmet"]/statBases</xpath>
Several helmets, like the S.A.C.R I and Exoskeleton helmets aren't patched.

2020-10-13 22:16 UTC, N7Huntsman commented on Patches/Orassans/ThingDefs_Misc/Apparel_Various.xml
> +					<xpath>/Defs/ThingDef[defName="Apparel_KittyArmor"]/statBases</xpath>
The exoskeletal armor also needs patched.

2020-10-18 19:59 UTC, Tostov commented
iirc, the mod also adds like, CatLavenderCloth or something, which is a devilstrand equivalent in vanilla and probably needs its stats reduced/fixed for CE levels and to be added to the soft armor catergory.

Also possibly the race's leathers.

2020-10-30 00:08 UTC, N7Huntsman approved these changes

2020-10-30 00:08 UTC, merged