Updated the translation for Simplified Chinese.
CombatExtended-Continued/CombatExtended pull request #3222
Opened 2024-06-29 17:23 UTC by 2805671972

Updated the translation for Simplified Chinese, fully aligning it with the latest content.

## Additions

Describe new functionality added by your code, e.g.
- Tribal smoke bombs
- New tribal smoke bomb sprite
- Tribal smoke bomb recipes at smithing bench and crafting spot using prometheum

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Increased regular smoke bomb radius

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #[ISSUE_NUMBER]
- Contributes towards #[ISSUE_NUMBER]

## Reasoning

Why did you choose to implement things this way, e.g.
- Tribals need ways to close distance with pirate raiders
- Smoke bombs allow this while enhancing combat micro
- Thematically appropriate as we already allow tribal prometheum handling
- Easy to implement
- Buffed regular smoke grenades as they are rarely utilized and to justify additional investment

## Alternatives

Describe alternative implementations you have considered, e.g.
- Tribal catapult that launches melee animals into siege camps:
  - Additional use for animals
  - Anachronistic
  - Breaks realism theme

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

2024-06-29 22:30 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/CombatExtended.AmmoSetDef/Mech.xml
> +  <AmmoSet_MechShell_Demo.label>机械族炮弹(演示)</AmmoSet_MechShell_Demo.label>
Demo here is supposed to mean demolition (爆破), **_not_** demonstration (演示)

2024-06-29 22:59 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.label>制作机械族炮弹 (演示) x5</MakeAmmo_MechShell_Demo.label>
Demo here is supposed to mean demolition (毁灭), **_not_** demonstration (演示)

2024-06-29 23:00 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <!-- EN: Craft 5 Mech Shells (Demo). -->
Demo here is supposed to mean demolition (毁灭), **_not_** demonstration (演示)

2024-06-29 23:00 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.description>制作机械族炮弹 (演示) x5。</MakeAmmo_MechShell_Demo.description>
Demo here is supposed to mean demolition (毁灭), **_not_** demonstration (演示)

2024-06-29 23:00 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.jobString>正在制作机械族炮弹 (演示)</MakeAmmo_MechShell_Demo.jobString>
Demo here is supposed to mean demolition (毁灭), **_not_** demonstration (演示)

2024-06-29 23:47 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/ThingDef/5x50mmCaseless.xml
> +\n\n脱壳穿甲弹:
The Simplified Mandarin text in the comments should be removed.

2024-06-30 00:00 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/ThingDef/Mech.xml
> +  <Ammo_MechShell_Demo.label>机械族炮弹 (演示)</Ammo_MechShell_Demo.label>
Demo here is supposed to mean demolition (破拆), **_not_** demonstration (演示)

2024-06-30 00:13 UTC, sumghai requested changes
@2805671972 - Most of the translation updates look good, but please fix the translations for the mechanoid demo(lition) ammo - "demo" in this context is supposed to mean demolition (爆破 or 破拆), **_not_** demonstration (演示)

2024-06-30 04:59 UTC, 2805671972 commented on Languages/ChineseSimplified/DefInjected/ThingDef/Mech.xml
> +  <Ammo_MechShell_Demo.label>机械族炮弹 (演示)</Ammo_MechShell_Demo.label>
The translation content has been revised

2024-06-30 07:20 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/CombatExtended.AmmoSetDef/Mech.xml
> +  <AmmoSet_MechShell_Demo.label>机械族炮弹(演示)</AmmoSet_MechShell_Demo.label>
Fixed by @2805671972 in 1343cac86db6aa7a1cafe99a467e5bd37f999f61

2024-06-30 07:20 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.label>制作机械族炮弹 (演示) x5</MakeAmmo_MechShell_Demo.label>
Fixed by @2805671972 in 1343cac86db6aa7a1cafe99a467e5bd37f999f61

2024-06-30 07:20 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.description>制作机械族炮弹 (演示) x5。</MakeAmmo_MechShell_Demo.description>
Fixed by @2805671972 in 1343cac86db6aa7a1cafe99a467e5bd37f999f61

2024-06-30 07:20 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/RecipeDef/Mech.xml
> +  <MakeAmmo_MechShell_Demo.jobString>正在制作机械族炮弹 (演示)</MakeAmmo_MechShell_Demo.jobString>
Fixed by @2805671972 in 1343cac86db6aa7a1cafe99a467e5bd37f999f61

2024-06-30 07:22 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/ThingDef/5x50mmCaseless.xml
> +\n\n脱壳穿甲弹:
I'll fix this myself later.

2024-06-30 07:23 UTC, sumghai commented on Languages/ChineseSimplified/DefInjected/ThingDef/Mech.xml
> +  <Ammo_MechShell_Demo.label>机械族炮弹 (演示)</Ammo_MechShell_Demo.label>
Fixed by @2805671972 in 1343cac86db6aa7a1cafe99a467e5bd37f999f61

2024-06-30 07:23 UTC, sumghai approved these changes

2024-06-30 07:29 UTC, merged