Non lerp projectile fixes
CombatExtended-Continued/CombatExtended pull request #3395
Opened 2024-09-04 03:46 UTC by CMDR-Bill-Doors

## Changes

Non lerp projectile's armor pen now scales with velocity.
Made non lerp projectile's acceleration function virtual.
Fixed various problems including non lerp projectile hitting nothing because of ticktoimpact
Moved acceleration function in front of actual move code.

## Reasoning

Having acceleration behind exactpos+=velocity means that I need to caculate the velocity needed next tick instead of current tick, which fucks with guided missile.

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] Playtested a colony (playing with missiles rn)

2024-09-09 04:32 UTC, perkinslr requested changes

2024-09-09 04:32 UTC, perkinslr commented on Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
> +            if ((lerpPosition && ticksToImpact <= 0) || nextPosition.y <= 0f)
We might need a _different_ flag here, but non-lerp projectiles can have unexpected or unspecified ticksToImpact values, as ticksToImpact isn't really a sensible value when the projectile is launched without a precalculated destination.  Maybe your stuff needs a time fuze type mechanism in play?

2024-09-09 06:02 UTC, perkinslr approved these changes

2024-09-17 01:24 UTC, N7Huntsman approved these changes
Nothing dramatically exploded during some general testing, so it seems we're alright.

2024-09-17 01:25 UTC, merged