Support arbitrary ammosets for siege artillery
CombatExtended-Continued/CombatExtended pull request #3530
Opened 2024-11-02 04:28 UTC by mszabo-wikia

## Additions

- Support for arbitrary ammosets for siege artillery

## Changes

The vanilla logic around sieges is fairly inflexible -- it mostly assumes that only 81mm mortars are used, which effectively prevents using modded artillery in sieges without hacks like the "raider artillery" in our VFE:S patch that consumes the 81mm ammoset.

So, rework our patches around sieges to support artillery pieces with arbitrary ammosets, and remove raider artillery.

## References

- Closes #3269

## Reasoning
The raider artillery was only ever a stopgap, and it'll be nice to have the flexibility to use any artillery type and ammunition in sieges.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony -- tested spawning sieges with VFE:S, with a mixture of mortars and 155mm artillery

2024-11-04 03:46 UTC, N7Huntsman approved these changes
Works correctly in my testing using VFE: Security, and it's dropping the appropriate ammo types.

2024-11-04 03:55 UTC, N7Huntsman commented on Source/CombatExtended/CombatExtended/SiegeUtility.cs
> +            MinRequiredConstructionSkill = DefDatabase<ThingDef>.AllDefsListForReading
Out of curiosity, how does vanilla handle making sure they spawn at least one pawn with high enough Construction to build the mortar? Do they have a dynamic check, or do they just make sure at least one has 5 construction (which is what mortars require)?

2024-11-04 03:57 UTC, N7Huntsman approved these changes

2024-11-07 01:24 UTC, N7Huntsman requested changes
With all DLCs loaded, everything works as intended (see my other review).

However, somewhere in here we've baked-in a dependency upon Biotech. There are no errors thrown if you play without Biotech, but sieges won't be supplied with shells.

2024-11-11 23:47 UTC, N7Huntsman approved these changes
After some adjustments to the checks, I'm satisfied with the state of things, and everything works as intended both with and without DLCs active.

2024-11-11 23:56 UTC, Thorbane approved these changes

2024-11-11 23:57 UTC, merged