Exclude melee from wall frags
CombatExtended-Continued/CombatExtended pull request #3572
Opened 2024-11-28 11:23 UTC by Safairette

## Changes

- Melee attacks now no longer create fragments when the fragments from walls are enabled

## Reasoning

- Using melee to break buildings/debris carries disproportionate risk with the setting enabled.
- Melee attacks *should* be the only instances of damage where the tool isn't null, so shouldn't affect anything else.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Gunshots still make the wall ouchies
- [ ] Playtested a colony (specify how long)

2024-11-29 21:02 UTC, MaxDorob approved these changes
As far as I understand it prevents d

2024-11-30 07:26 UTC, N7Huntsman requested changes
Failing to prevent the issue; still getting fragments spawning attacking walls with longsword, zeushammer, mace, and bare fists.

2024-11-30 10:03 UTC, MaxDorob approved these changes

2024-11-30 21:05 UTC, N7Huntsman approved these changes

2024-11-30 21:05 UTC, merged