Spaceworm
CombatExtended-Continued/CombatExtended pull request #483
Opened 2021-01-16 05:14 UTC by Breadbox2k19

## Additions

Spaceworm

Check tests you have performed:
- [x ] Compiles without warnings
- [x ] Game runs without errors
- [x ] (For compatibility patches) ...with and without patched mod loaded
- [x ] Playtested a colony (specify how long)

2021-01-17 03:28 UTC, N7Huntsman requested changes

2021-01-17 03:28 UTC, N7Huntsman commented on Patches/Spaceworm/Spaceworm.xml
> +				<xpath>/Defs/ThingDef[defName="FaceTeeth"]</xpath>
FaceTeeth is the defName of the BodyPartGroupDef. The defName for the creature is Scuttlebug.

2021-01-17 03:28 UTC, N7Huntsman commented on Patches/Spaceworm/Spaceworm.xml
> +							<linkedBodyPartsGroup>Teeth</linkedBodyPartsGroup>
Duplicate linkedBodyPartsGroup tag here. Remove the Teeth one, keep the Mouth one.

2021-01-17 03:36 UTC, N7Huntsman requested changes

2021-01-17 03:36 UTC, N7Huntsman commented on Patches/Spaceworm/Spaceworm.xml
> +						</li>
I'd do away w/ the headattacktool entirely, honestly. Just add `ensureLinkedBodyPartsGroupAlwaysUsable` to the mouth attack.

2021-01-17 23:38 UTC, Breadbox2k19 commented
All done.

2021-01-18 18:40 UTC, N7Huntsman commented
> All done.

Sorry, to clarify what I said about removing the headattacktool, I would do away with the second blunt attack entirely, since the worms' gimmick is their bite attack that implants what are basically chest-bursters. When you do this, I'd add the `ensureLinkedBodyPartsGroupAlwaysUsable` to the mouth attack, just to ensure they can't be left w/o an attack on the off chance one gets their jaw destroyed.

2021-01-19 02:21 UTC, N7Huntsman approved these changes
Generally in good shape, I'll make a couple of quick revisions.

2021-01-19 02:21 UTC, merged