[HLX] ReGrowth - Mutated Animals Pack
CombatExtended-Continued/CombatExtended pull request #493
Opened 2021-01-24 11:20 UTC by Breadbox2k19

## Additions

Patchy for a mod.
Untested WIP, if anyone's interested in testing, please report red errors.

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Increased regular smoke bomb radius

## References

## Reasoning

## Alternatives

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-01-24 21:05 UTC, N7Huntsman requested changes
In addition to a few specific changes to be made, more generally I'd also like you to tidy up the formatting a bit; make the alignment a bit more uniform, etc.

2021-01-27 07:01 UTC, Breadbox2k19 reviewed
Mod finalised, let me know if there are any errors on your end.

2021-01-28 18:00 UTC, N7Huntsman commented on Patches/[HLX] ReGrowth - Mutated Animals Pack/Deffclaw.xml
> +						<bodyShape>Birdlike</bodyShape>
I disagree. Quadruped *perhaps,* but Birdlike is intended for things with comparatively long, thin necks. necks, such as emu, ostriches. It's certainly not appropriate for a Deathclaw.

2021-01-28 19:43 UTC, Breadbox2k19 commented on Patches/[HLX] ReGrowth - Mutated Animals Pack/Deffclaw.xml
> +						<bodyShape>Birdlike</bodyShape>
Doesn't birdlike simply meant height x0.75 and width x1 . Of course deathclaw doesn't have a long neck or anything, bird, like is simply meant to represent the fact that death claw doesn't stand up straight and is as wide as is it is tall.

2021-01-31 05:35 UTC, N7Huntsman approved these changes
Everything seems good, pending a quick look into an odd start-up error.

2021-02-01 03:40 UTC, N7Huntsman approved these changes

2021-02-01 03:40 UTC, merged