Patch Not Only Just a Cannon
CombatExtended-Continued/CombatExtended pull request #532
Opened 2021-02-12 16:31 UTC by Person243546

## Additions

Added Patch for Not Only Just a Cannon. The Sieges don't bring the correct ammo yet.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-02-15 13:16 UTC, N7Huntsman requested changes
There's also a "Dragonator" cannon that needs to be either patched or removed. Something should be done with it one way or another.

2021-02-15 13:16 UTC, N7Huntsman commented on Patches/Not Only Just A Cannon/Patch_Cannon_Ammo.xml
> +				  <casingMoteDefname>Mote_BigShell</casingMoteDefname>
These shells probably shouldn't have a mote.

2021-02-15 13:21 UTC, N7Huntsman requested changes

2021-02-15 13:21 UTC, N7Huntsman commented on Patches/Not Only Just A Cannon/Patch_Cannon_Turret.xml
> +			<noSingleShot>true</noSingleShot>
These guns should match the existing flak cannon in that they should only have single shot mode appear on the gizmo, as opposed to fully automatic like they do now.

2021-02-18 15:45 UTC, Person243546 commented
The Dragonator has been patched now. (may be a bit op)

2021-03-17 22:45 UTC, N7Huntsman commented
> The Dragonator has been patched now. (may be a bit op)

Well, it's currently only got a range of about 12. I think you mixed up range and minrange.

2021-03-19 11:12 UTC, Person243546 commented
It originally had a range of 2 so it was a close range one hit kill weapon. (I think they meant to make it a melee turret)

2021-03-26 06:13 UTC, N7Huntsman approved these changes

2021-03-26 06:13 UTC, merged