Midworld weapons patch
CombatExtended-Continued/CombatExtended pull request #547
Opened 2021-02-25 15:38 UTC by Safairette

## Additions

A patch for Midworld Weaponry Expanded, uploaded on behalf of Pan de un Goblin

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-02-25 23:36 UTC, T-rexsuper1 commented
Yess I did it! Thanks for help with github!

2021-02-27 21:39 UTC, N7Huntsman requested changes
A tweak to suggest.

2021-02-27 21:39 UTC, N7Huntsman commented on Patches/Midworld Weaponry Expanded/Industrial_Ranged.xml
> +				<SwayFactor>1.15</SwayFactor>
This is probably a bit too low for a heavier weapon that doesn't have a stock. I know it's a two-handed weapon, but for stat purposes, I'd calculate it as a one-handed weapon and perhaps reduce it from there a bit.

2021-03-08 07:48 UTC, N7Huntsman approved these changes

2021-03-08 07:49 UTC, merged