Additional Vanilla Weapons Expanded patch work.
CombatExtended-Continued/CombatExtended pull request #618
Opened 2021-04-18 00:38 UTC by N7Huntsman

- Add High Roller variants of projectiles, with a 10% chance to double damage.
- Patch Vanilla Weapons Expanded - Tribal (Complete).
- Patch Vanilla Weapons Expanded - Non-lethal (WIP).

2021-04-21 14:26 UTC, Tostov requested changes
Shards have too much damage and penetration, somehow outdoing the damage that stabbing someone with a knife directly, when thrown. This is backwards since a knife has the actual mass of someone behind it rather than just its own mass from being tossed.

Firebombs have a duplicate recipe that probably remains from the weapon's thingdef itself most likley.

The taser works acceptably at the moment, but it would be worth considering re-working it to use the muscle spasms system since at the moment it can stun-lock anything regardless of its armor. Which is interesting but maybe a bit too strong.

Otherwise seems good.

2021-04-23 00:33 UTC, Tostov requested changes
The ammoset on the sentry is incorrectly defined. Haven't run into anything else during quick tests.

2021-04-23 00:33 UTC, Tostov commented on Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
> +          <ammoSet>Ammo_556x45mmNATO_FMJ</ammoSet>
Typo'd the ammo in rather than the ammoset. Otherwise all good

2021-04-23 01:33 UTC, Tostov approved these changes

2021-04-23 01:34 UTC, merged

2021-04-23 21:29 UTC, P4V3L-3D0TS commented
what about 40mm bean bag?