[O21] Outer Rim Galaxies patch
CombatExtended-Continued/CombatExtended pull request #656
Opened 2021-05-10 14:12 UTC by Person243546

## Additions

Adds a compatibility patch for [O21] Outer Rim Galaxies [DevBuild].

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-05-11 23:23 UTC, N7Huntsman requested changes
A very quick and dirty first pass pointing out a couple errors. I'll do a more detailed review later on, but since the base mod is still currently a dev build, it's likely too unstable to merge a patch for at the moment.

2021-05-11 23:23 UTC, N7Huntsman commented on Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Apparel.xml
> +					<StuffEffectMultiplierArmor>3</StuffEffectMultiplierArmor>
This `StuffEffectMultiplierArmor` is a duplicate node.

2021-05-12 15:08 UTC, Person243546 commented on Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Weapons.xml
> +		<li>[O21] Outer Rim Galaxies [DevBuild]</li>
Should be fixed now

2021-05-12 15:14 UTC, Person243546 commented on Patches/[O21] Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_Weapons.xml
> +		<li>[O21] Outer Rim Galaxies [DevBuild]</li>
Fixed. All the patches for optional content should have a conditional patch now.

2021-05-31 16:06 UTC, closed without merging