Tweak Spartan Foundry
CombatExtended-Continued/CombatExtended pull request #658
Opened 2021-05-13 04:48 UTC by Endur1el

## Changes

Tweaked the values of Spartan foundry armor to better reflect it's place as uncraftable (with one exception), end-game armor that doesn't have prestige variants.

## Reasoning

Made a list as follows with vanilla stats:

### Armor
recon 92% -> 16mm
marine 106% -> 20mm
cataphract 120% -> 28mm
### Helmets
recon 92% -> 12mm
marine 106% -> 16mm
cataphract 120% -> 22mm

and then placed the spartan foundry armor as seemed appropriate by their armor values compared to the above values, with preference for multiples of 2 and exclusively using whole numbers. This then gave me the following list: 

### Armor:
powered assault 118% -> 28mm +
engineer 108% -> 22mm +
explorer 90% -> 18mm ++
grenadier 148% -> 32mm --
commando 108% -> 22mm +
hazard 112% -> 24mm +
diplomat 112% -> 24mm +
defender 108% -> 22mm +
scout 105% -> 20mm +
samurai 85% -> 16mm +
shock 100% -> 19mm +
recon 105% -> 20mm +

### Helmets:
powered assault 110% -> 20mm +
engineer 100% -> 16mm +
explorer 88% -> 14mm ++
grenadier 110% -> 20mm +
commando 100% -> 16mm +
hazard 100% -> 16mm +
diplomat 100% -> 16mm +
defender 112% -> 21mm +
scout 100% -> 16mm +
samurai 100% -> 16mm +
shock 100% -> 16mm +
recon 80% -> 12mm ++

The +/- reflects armor whether the stats are higher/lower than the appropriate value at the curve between the vanilla armors. Most of these can be justified as rounding up to a multiple of 2 to make the armor slightly stronger considering it is uncraftable (or requires an AI core).

The exceptions are:
- An all-round buff to explorer to make it between recon and marine armor so it is more viable as it's buffs to farming and animal husbandry aren't particularly impressive.
- A heavy nerf to the chest armor of grenadier armor, which still puts it at 32mm but now at least it's not as insanely strong as it's vanilla counterpart.
- A buff to the recon helmet so it's not weaker than actual marine armor.

2021-05-13 05:08 UTC, Tostov requested changes
So, the thing about cataphract armor is that it has, at best a neutral carry to weight ratio, i.e. the carry weight bonus implemented by the armor is equal to the weight of the armor, addtionally cataphract's base weight is higher than that of other power armor variants, at 80kg vs the general 60kg.

Addtionally, while the base market value of the armor is higher than that of conventional power armor, it is lower than that of cataphract armor, and even if factoring in the item only status, the techprint requirement for cataphract does create a simmilar situation.

I'd like you to resolve these two disrepencies with cataphract if you're going to use it as a base for the armor's defensive specs. Keep in mind that the armor ratios are not a flat 1:1 vanilla to CE conversion, and for example, the explorer power armor reasonably should only have the same protection as recon armor, as it currently does, for example.

Otherwise, I'd like you to provide some serious justification as to why the values should be changed. From my understanding the armor isn't specifically very weak in the first place.

2021-05-13 05:41 UTC, Endur1el commented
Before I go into it too far, maybe my issue is instead with the patch for Vanilla Armor Expanded. Specifically Siegebreaker and Trooper armor. Maybe they need to be nerfed instead, because right now they seem to be by far the best armors in my vanilla++ modlist. They have better stats than almost all of the above, with an overshield, or allowing dusters. They have better weight vs carry than cataphract as well.

In comparison, the stuff in here _can't_ be crafted, and I personally think that there should be a much greater power difference between the armors because of it, right now the only difference is in the, admittedly impressive, durability of these armors, but this is either mostly inconsequential if you have something that allows repairs, or just means you get a temporary bonus for somewhat longer because once it's gone, it's gone.

2021-05-13 06:36 UTC, Tostov commented
Trooper _is_ getting nerfed, and I'd agree that siegebreaker is OP at the moment.

That being said, it's fair enough, barring the one exception of powered assault which I believe should sit at most at 26mm, which makes it a high mobility equivalent to siegebreaker armor, and it's buildable in the first place anyway.

Anyway. Given that as the case, the blunt armor values should also be updated to reflect the new sharp values, since in general the two values are largely stuck together in CE. This general value is 2.25, but if you wanted to go into more detail, realistically the Spartan foundry armors can be split roughly into three blunt brackets in vanilla:
Mid: Powered Assault, Explorer, grenadier, diplomat
High: Engineer, Shock, Recon
Low: Com, Haz, scout, samurai

You may want to consider using 2/2.25/2.5 for the low/mid/high blunt ratios instead, or even 2.25/2.5/2.75, though I would move Powered assault armor down to the low bracket since it's buildable, if you were to use the increased values.

2021-05-13 07:17 UTC, Endur1el commented
That's all the blunt changes, decided to go with 2.25-2.75 as vanilla armors are 2.5 and this way some have better blunt ratios than vanilla which adds better variety imo. Also treated defender as high, and powered assault as low. I also adjusted powered assault to 26mm as you made a good point, though I'd argue requiring an AI core still sets the bar pretty high on crafting costs compared to other stuff, but if Siegebreaker gets nerfed I have no issues with those stats.

Thanks for being open to discussion and genuinely helpful. Also I somehow never realized CE blunt was a multiplier on sharp so that's good to know.

2021-05-13 08:18 UTC, Tostov approved these changes
I'll approve it, but probably best to let it sit until N7 or whoever did the original patch just double checks, especially since there most likely won't be a update to CE for a while.

Also one last thing, is that I'd suggest taking a look at the grenadier armor's other stats, as this patch makes it extremely strong combat armor with very little/no drawbacks. Making it heavier than its carry weight offset may be worth considering, or failing that, applying a bit of a movespeed penalty. <RangedWeapon_Cooldown>-0.3</RangedWeapon_Cooldown> on it should be swapped with a reload speed buff, since that's realistically what it's actually supposed to represent, especially given that the description does say 'faster reload speed' on the mod page.

2021-05-13 17:48 UTC, AluminumAlman commented
I'm looking over the changes, and here are my thoughts:
- Powered assault armor could have 22 sharp armor and 55 blunt armor - graphic looks like a slightly more armored variant of marine armor;
- Engineer power armor could have 20 sharp armor and 65 blunt armor - graphic looks like a better version of marine armor, but the vanilla sharp armor value of engineer power armor is the same as marine armor and the armor's description is stated to be made to protect against blunt trauma better;
- Explorer power armor armor values are perfect;
- Grenadier power armor could have 24 sharp armor and 60 blunt armor - graphic is similar to Vanilla Armor Expanded siegebreaker armor, except it looks less bulky (though this reminds me that I should buff the siegebreaker armor next time), description suggests it's more armored and a bit more focused on blunt armor, also I agree with Tostov - the negative weapon cooldown multiplier offset should be switched out with a positive reload speed offset;
- Commando power armor armor values are perfect;
- Hazard operations power armor could have 20 sharp armor and 45 blunt armor - it is power armor meant to protect against hazardous environments, so it having better ballistic protection than marine armor wouldn't make sense;
- Diplomat power armor could have 22 sharp armor and 49.5 blunt armor - looks like a slight upgrade over marine armor.

Of course the suggested value changes can be discussed further, and any change should have the armors' helmets' armor values updated.

2021-05-13 19:56 UTC, Endur1el commented
@AluminumAlman honestly I can get behind most of that, though I don't like using graphics as an indicator of performance, especially for stuff which is uncraftable (implying it is beyond the tech of the player).

My one disagreement is with grenadier, it's the special, uncraftable armor meant for tankiness, it _should_ be better than cataphract and this is reflected in its (admittedly insane) vanilla stats. I'm not saying we should follow those one-to-one, but making it weaker than cataphract doesn't really make much sense to me, especially considering how it's easier to craft high-rarity cataphract than buy high-rarity grenadier, making the difference even more stark. Perhaps the right solution would be to make it heavier and have its carry weight = its mass, something like 100/100.

Also I hope you're joking about siegebreaker because it genuinely is OP right now, especially since it has a prestige variant which none of this stuff does.

2021-05-14 06:12 UTC, AluminumAlman commented
> My one disagreement is with grenadier, it's the special, uncraftable armor meant for tankiness, it _should_ be better than cataphract and this is reflected in its (admittedly insane) vanilla stats. I'm not saying we should follow those one-to-one, but making it weaker than cataphract doesn't really make much sense to me, especially considering how it's easier to craft high-rarity cataphract than buy high-rarity grenadier, making the difference even more stark. Perhaps the right solution would be to make it heavier and have its carry weight = its mass, something like 100/100.
> 
> Also I hope you're joking about siegebreaker because it genuinely is OP right now, especially since it has a prestige variant which none of this stuff does.

Thanks to you, I compared the sharp armor values of vanilla cataphract and vanilla grenadier. I guess it'd be better if grenadier power armor had 28 sharp armor and 91 blunt armor then, since the description says "<...> upgraded to withstand violent concussive force. <...> grenadier power armor provides users with extra protection from explosive devices." I've checked the projectile stat sheet, and 91 blunt armor should be enough to let a pawn survive a direct hit from a 120mm HE shell. Though it'd still be great to hear your thoughts on it.

Oh, and by siegebreaker armor buffs, I'll compare the stats and recipe costs between cataphract and siegebreaker armor and do some tweaks to the stats and/or recipe.

2021-05-14 06:57 UTC, Tostov commented
imo, siegebreaker needs [100/100] [weight/carry bonus] and/or even a hard reduction to movespeed. In vanilla it has a whopping -1.1 movespeed, compared to even cataphract's -0.8. Not only is it entirely comparable in defense as is currently, but as is it provides better carry bulk/mass compared to cataphract _and_ has a built in ranged shield belt, and costs the same practically.

Characteristically, despite the description, siegebreaker armor should be slowing the pawn down. Other than that its stats are fine, imo.

2021-05-15 07:14 UTC, Endur1el commented
First off sorry about confusing you with regards to grenadier @AluminumAlman, if it helps I've gotten lost a couple times here as well (although it's been recon for me lol). You make a good point about the grenadier power armor so I've implement the changes to make it cataphract in terms of sharp but with much better blunt.

I gave diplomat 55 instead of 29.5 though because if we do go by graphic it looks a significantly bulkier than marine and it's non-CE stats are actually a fair bit better than vanilla marine so I think this is a good compromise.

Also upon further reflection I don't really think making power armor weaker is a good idea, it may be craftable but it takes an AI core, and this still only puts in on par with siegebreaker. Also I'd argue the graphics look equally as tanky and in terms of non-CE stats (and these are both by the same author remember) powered assault is decently better than siegebreaker armor. I think it's fine to leave it as is with 26mm and 59 MPa of armor.

2021-05-16 10:59 UTC, AluminumAlman approved these changes

2021-05-17 16:16 UTC, N7Huntsman approved these changes

2021-05-17 16:16 UTC, merged