Nyaron Race patch
CombatExtended-Continued/CombatExtended pull request #676
Opened 2021-05-23 15:03 UTC by Tostov

## Additions

Add CE relevant stuff for Nyaron Race. Race specs themself are from the author's original patch.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] Playtested a colony (specify how long)

2021-05-24 13:26 UTC, Breadbox2k19 commented
UwU WuW Tostov I never knew you are the type that's into anime cat girls UwU WuW

2021-05-24 18:53 UTC, N7Huntsman requested changes
Contents look fine, but the formatting needs cleaned up a bit.

2021-05-24 18:53 UTC, N7Huntsman commented on Patches/Nyaron/Ammo/Ammo_Nyaron.xml
> +		<match Class="PatchOperationSequence">
Double nested Patch Op Sequence?? Clean this up a bit, please. You only really need the single FindMod op with a `<match Class="PatchOperationAdd">` and add both ammo sets at once.

2021-05-24 18:53 UTC, N7Huntsman commented on Patches/Nyaron/ThingDefs_Items/Items_Resources.xml
> +		<success></success>
?

2021-05-25 01:58 UTC, N7Huntsman approved these changes

2021-05-25 01:58 UTC, merged