increase ogron armor to feral mail level
CombatExtended-Continued/CombatExtended pull request #699
Opened 2021-05-31 22:31 UTC by heavenisaplaceonearth1

Ogron armor was initially 1.5 sharp and 0.5 blunt, probably a leftover from the old armor system. Since the different ogron classes (hellmaker, gutcher, orgenaut) use the same race_ogron armor, I decided to only up the armor to 8 sharp and 8 blunt, which is what the current feral mail armor is. Hopefully it'll give the ogrons enough survivability while not making it too tanky given its health pool.

## Additions

Describe new functionality added by your code, e.g.
- Buffs Ogrons 

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Increased ogron armor to 8 sharp and 8 blunt, the armor level used for feral mail

## Reasoning

Why did you choose to implement things this way, e.g.
- Ogrons were easy to down due to lack of armor (1.5 sharp and 0.5 blunt currently)
- increases ogron survivability 
- Easy to implement

## Testing

Check tests you have performed:
- [x ] Compiles without warnings
- [ x] Game runs without errors
- [x ] (For compatibility patches) ...with and without patched mod loaded
- [x ] Playtested a colony (specify how long)

2021-06-01 02:32 UTC, Tostov requested changes
Rather than raising both to 8, I'd suggest instead only raising the sharp proteciton to 8 and leaving the blunt protection fairly low at 1-2ish or so, which should permit blunt force melee weapons and some of the heavier hitting sharp weapons to still deal reasonable damage. This largely won't affect gun firepower towards them since most firearm rounds massively exceed the 8 blunt armor they have anyway.

This prevents them from accidentally becoming a hard-block to tribals early on, especially given that unlike mechanoids, ferals can raid immediately.

2021-06-01 05:09 UTC, heavenisaplaceonearth1 commented
lowered blunt armor to 2

2021-06-02 02:19 UTC, Breadbox2k19 commented
I suggest adding a new body type mostly limits its armour coverage to mostly and then patching to replace the bodytype of the ogron race. I'll do it when I got the time.

2021-06-03 02:19 UTC, Tostov commented
> I suggest adding a new body type mostly its armour coverage to mostly and then patching to replace the bodytype of the ogron race. I'll do it when I got the time.

This seems pretty reasonable tbh, though I'm always reluctant about adding new bodydefs.

2021-06-09 01:43 UTC, N7Huntsman approved these changes

2021-06-09 01:45 UTC, N7Huntsman commented
Approved, as it adjusts the armor as intended. If a different bodyType for the Ogrons is desired, it can probably be submitted as a new PR to get this change merged.

2021-06-10 03:04 UTC, N7Huntsman approved these changes

2021-06-10 11:16 UTC, Tostov approved these changes

2021-06-10 11:17 UTC, merged