Melee weapons tweak
CombatExtended-Continued/CombatExtended pull request #840
Opened 2021-07-23 03:36 UTC by Breadbox2k19

## Additions
I personally find the long sword deeply underwhelming, its stab attack is slow and does low damage. So I buffed it abit to make it less underwhelming.

I'd like to change the quality modifier for melee weapons in the the future, lower its effect on weapon melee damage output and more effect on weapon melee penetration.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

2021-07-23 04:07 UTC, Tostov requested changes
Sheet with updated info where?

Keep in mind that we can get any value we want out of the sheet pretty much, but for consistency's sake I'd really appreciate if you had one so it's easier to make adjustments in the future if required rather than just eyeballing it.

2021-07-23 07:18 UTC, Breadbox2k19 commented
> Sheet with updated info where?
> 
> Keep in mind that we can get any value we want out of the sheet pretty much, but for consistency's sake I'd really appreciate if you had one so it's easier to make adjustments in the future if required rather than just eyeballing it.

If the sheet doesn't result in good balance(most of the time it does not, resulting in tons of melee weapon that isn't good at anything), then I say tweak it with eyeballs.

2021-07-23 07:33 UTC, Tostov commented
Sheet can literally spit out whatever values you'd like with the right coercion, at least for sharp stuff. Blunt pen is always mass velocity dependant, but yeah. People do externally use these sheets and we mostly internally use the rules from them.
Added the changed longsword stat and spear stats here for reference 
https://docs.google.com/spreadsheets/d/1kE53Zjlb8GzLGl9bjYQYWOYgotIGULiyqpZi6uZlnbg/edit?usp=sharing
Knife change is near pointless and probably fine to revert.

2021-08-24 05:22 UTC, N7Huntsman approved these changes

2021-08-24 05:23 UTC, merged