Rimsenal update 1.3
CombatExtended-Continued/CombatExtended pull request #853
Opened 2021-07-25 11:18 UTC by Tostov

## Additions

Added patch for charge frontier rifle

## Changes

Added nightvision stats.
Fixed some of the federation stuff that had broke and added in the stats for the duplicate baton used by the bion NPC

## Testing

Check tests you have performed:
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-07-25 11:45 UTC, Breadbox2k19 commented
With muzzle flash reducing darkness next patch, I think some of the weapons could use a lower muzzle flash scale of around 2-3.

2021-07-25 11:58 UTC, Tostov commented
iirc most the weapons have fairly normal muzzle flash, but I can reduce them if you want to point out specific ones to do it on.

2021-07-25 19:11 UTC, N7Huntsman requested changes
The Security/Patch_Security.xml patch is failing.

2021-07-27 05:44 UTC, N7Huntsman approved these changes

2021-07-27 05:44 UTC, merged