Medieval Overhaul by Boldizsár
CombatExtended-Continued/CombatExtended pull request #970
Opened 2021-08-16 21:14 UTC by Safairette

## Patch is done by Boldizsár, all complaints/suggestions should be sent to them

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-08-17 01:14 UTC, Breadbox2k19 commented
I suggest adding the nosetag into base CE patches, there are plenty of apparels that covers the nose but not the eye.

2021-08-17 09:44 UTC, N7Huntsman requested changes

2021-08-17 09:44 UTC, N7Huntsman commented on Patches/Medieval Overhaul/MO_Traits.xml
> +              <commonality>0</commonality>
What's this?

2021-08-17 09:44 UTC, N7Huntsman commented on Patches/Medieval Overhaul/MO_Materials.xml
> +					<StuffPower_Armor_Sharp>0.12</StuffPower_Armor_Sharp>
I'm getting a duplicate error associated with this.

2021-08-17 09:44 UTC, N7Huntsman commented on Patches/Medieval Overhaul/MO_Materials.xml
> +					<StuffPower_Armor_Sharp>0.14</StuffPower_Armor_Sharp>
I'm also getting an error associated with this operation.

2021-08-23 15:20 UTC, N7Huntsman requested changes
I can't get the ballista or trebuchet working. Additionally, the ballista bolts added by the mod can probably be removed.

2021-09-03 05:09 UTC, N7Huntsman requested changes
- Tavern Owner scenario needs ammo for bow.
- Chain mail helmets stats are a little too high. I'd make them slightly weaker than plate helmets.
- Stuffable helmets need Steeled instead of metallic. (Iron will probably need this tag added).
- Rox horn needs turned into a resource.
- Ballista bolts should be removed, since the turrets uses javelin for ammo.

2021-09-04 00:35 UTC, N7Huntsman commented
I've copied the files and have made all the changes I noted above. For expediency, I'm closing this PR, and will make a new one with the updated files.

2021-09-04 00:35 UTC, closed without merging