Add files via upload
CombatExtended-Continued/CombatExtended pull request #977
Opened 2021-08-19 05:22 UTC by Breadbox2k19

Update and fixes for the following mods
-Contractor arsenal
-Rimeffect mods
-The Joris Experience

## Testing

Check tests you have performed:
- [ ] Compiles without warnings
- [ ] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [ ] Playtested a colony (specify how long)

2021-08-23 04:19 UTC, N7Huntsman requested changes
I don't like what you've done with the 410 bore and the 12 gauge. Where did these numbers from from?

Additionally, yes, the Bible joris is still shooting sideways.

2021-08-24 06:12 UTC, Breadbox2k19 commented on Defs/Ammo/Shotgun/410Bore.xml
> -      <speed>70</speed>
The numbers are clearly based on the 12 gauge buckshot fired from a shotgun, there's no way that the .410 buck fired from a snub nose revolver is going to be as fast.
The numbers are from .45 colt.

2021-08-24 06:18 UTC, Breadbox2k19 commented on Defs/Ammo/Shotgun/12Gauge.xml
> +      <armorPenetrationSharp>3.5</armorPenetrationSharp>
No exact numbers sorry, It's just clearly wrong how smaller/identical sized projectiles fired from a pistol somehow has more energy than projectiles fired from a long barrel shotgun.

2021-08-24 17:13 UTC, N7Huntsman commented on Defs/Ammo/Shotgun/410Bore.xml
> -      <speed>70</speed>
If that's what this is intended to address, I might set up something like the musket ball fast/slow ammosets. One with projectiles for a full-length barrel, another with something for the shorter barrel.

2021-08-31 02:52 UTC, Breadbox2k19 commented on Defs/Ammo/Shotgun/12Gauge.xml
> +      <armorPenetrationSharp>3.5</armorPenetrationSharp>
> Source on these numbers?

If you aren't happy with these changes, then pls approve the bugfixes and update portion without them.

2021-09-02 06:32 UTC, N7Huntsman approved these changes

2021-09-02 06:33 UTC, merged